/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { User1WhereUniqueInput } from "./User1WhereUniqueInput";
import { User1UpdateInput } from "./User1UpdateInput";

@ArgsType()
class UpdateUser1Args {
  @Field(() => User1WhereUniqueInput, { nullable: false })
  where!: User1WhereUniqueInput;
  @Field(() => User1UpdateInput, { nullable: false })
  data!: User1UpdateInput;
}

export { UpdateUser1Args as UpdateUser1Args };
