/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateUser1Args } from "./CreateUser1Args";
import { UpdateUser1Args } from "./UpdateUser1Args";
import { DeleteUser1Args } from "./DeleteUser1Args";
import { User1FindManyArgs } from "./User1FindManyArgs";
import { User1FindUniqueArgs } from "./User1FindUniqueArgs";
import { User1 } from "./User1";
import { User1Service } from "../user1.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => User1)
export class User1ResolverBase {
  constructor(
    protected readonly service: User1Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "User1",
    action: "read",
    possession: "any",
  })
  async _user1sMeta(
    @graphql.Args() args: User1FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [User1])
  @nestAccessControl.UseRoles({
    resource: "User1",
    action: "read",
    possession: "any",
  })
  async user1s(@graphql.Args() args: User1FindManyArgs): Promise<User1[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => User1, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User1",
    action: "read",
    possession: "own",
  })
  async user1(
    @graphql.Args() args: User1FindUniqueArgs
  ): Promise<User1 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => User1)
  @nestAccessControl.UseRoles({
    resource: "User1",
    action: "create",
    possession: "any",
  })
  async createUser1(@graphql.Args() args: CreateUser1Args): Promise<User1> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => User1)
  @nestAccessControl.UseRoles({
    resource: "User1",
    action: "update",
    possession: "any",
  })
  async updateUser1(
    @graphql.Args() args: UpdateUser1Args
  ): Promise<User1 | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => User1)
  @nestAccessControl.UseRoles({
    resource: "User1",
    action: "delete",
    possession: "any",
  })
  async deleteUser1(
    @graphql.Args() args: DeleteUser1Args
  ): Promise<User1 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
