/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { User1WhereInput } from "./User1WhereInput";
import { Type } from "class-transformer";
import { User1OrderByInput } from "./User1OrderByInput";

@ArgsType()
class User1FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => User1WhereInput,
  })
  @Field(() => User1WhereInput, { nullable: true })
  @Type(() => User1WhereInput)
  where?: User1WhereInput;

  @ApiProperty({
    required: false,
    type: [User1OrderByInput],
  })
  @Field(() => [User1OrderByInput], { nullable: true })
  @Type(() => User1OrderByInput)
  orderBy?: Array<User1OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { User1FindManyArgs as User1FindManyArgs };
