/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { User1WhereInput } from "./User1WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class User1ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => User1WhereInput,
  })
  @ValidateNested()
  @Type(() => User1WhereInput)
  @IsOptional()
  @Field(() => User1WhereInput, {
    nullable: true,
  })
  every?: User1WhereInput;

  @ApiProperty({
    required: false,
    type: () => User1WhereInput,
  })
  @ValidateNested()
  @Type(() => User1WhereInput)
  @IsOptional()
  @Field(() => User1WhereInput, {
    nullable: true,
  })
  some?: User1WhereInput;

  @ApiProperty({
    required: false,
    type: () => User1WhereInput,
  })
  @ValidateNested()
  @Type(() => User1WhereInput)
  @IsOptional()
  @Field(() => User1WhereInput, {
    nullable: true,
  })
  none?: User1WhereInput;
}
export { User1ListRelationFilter as User1ListRelationFilter };
